services:
  postgres:
    image: postgres:16
    container_name: postgresql
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: ./app
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./telegramBot/imgs:/imgs
  bot:
    build: ./telegramBot
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./telegramBot/imgs:/app/imgs
volumes:
  pgdata:
